        <div class="wa-stack ">

          <wa-tooltip for="carousel-item-0" placement="left" hoist>Presenting our SPINE Programming Theory research paper to the NEDSI community. </wa-tooltip>
          <wa-tooltip for="carousel-item-1" placement="left" hoist>Christopher Tate and Dewayne Branch at last year's NEDSI 2025 research conference in Hershey, Pennsylvania. </wa-tooltip>

          <wa-carousel style="--aspect-ratio: 16/4; " autoplay loop navigation pagination autoplay-interval="5000">
            <wa-carousel-item>
              <img id="carousel-item-0" src="{{ STATIC_BASE_URL }}{{ result.pageImageUri }}">
            </wa-carousel-item>
            <wa-carousel-item>
              <img id="carousel-item-1" src="{{ STATIC_BASE_URL }}/jpg/nedsi-conference-2025.jpg">
            </wa-carousel-item>
          </wa-carousel>

          <p>
            Join us in Philadelphia, PA Thu Apr 9 - Sat Apr 11, 2026 at the NEDSI 2026 conference, 
            with other scholars and practitioners interested in the application of 
            quantitative and behavioral methods to the problems of society through emerging technology. 
          </p>
          <p>
            We will be presenting SPINE Programming Theory, 
            a form of on-device, local, sovereign AI code indexing and open source code generation of data-driven websites and digital twins. 
          </p>
          <p>
            You can read the <a href="https://docs.google.com/document/d/1whyZNMopmAQ14XZCxC_qfswcBgrmaKoRRcFUvy6GNLw/edit?usp=sharing">API Code Generation of Zero Trust, Data-driven Websites, Digital Twins with SPINE Programming Theory research paper here</a>. 
          </p>

          <wa-card with-header>
            <div slot="header">
              <div class="wa-flank ">
                <i class="fa-duotone fa-regular fa-conveyor-belt fa-8x "></i>
                <div>
                  <h2 class="brand-font anchor-heading">
                    About the conference
                    Generative AI to Enhance Supply Chain Resilience
                  </h2>
                </div>
              </div>
            </div>
            <div class="wa-stack ">
              <div>
                <p>
                  The 2026 conference theme, Future of Decision Sciences: Complexity, Innovation, Sustainability, invites us to reflect critically and constructively on the evolution of our field and the role it must play in addressing modern organizational and societal challenges. 
                  The program will feature a vibrant mix of paper sessions, panel discussions, interactive workshops, and student posters, with an emphasis on interdisciplinary collaboration and real-world application. 
                  A NEDSI conference is a forum for scholars and practitioners to present their research in their areas of expertise and interlace into new horizons, 
                  it is where salient networking occurs, and friendships are made for a lifetime. 
                </p>
              </div>
            </div>
          </wa-card>
        </div>
