<div class="wa-stack ">

          <wa-tooltip for="carousel-item-0" placement="left" hoist>Présentation de notre document de recherche sur la théorie de la programmation SPINE à la communauté NEDSI. [cite: 1, 2]
          </wa-tooltip>
          <wa-tooltip for="carousel-item-1" placement="left" hoist>Christopher Tate et Dewayne Branch lors de la conférence de recherche NEDSI 2025 l'année dernière à Hershey, en Pennsylvanie. [cite: 3]
          </wa-tooltip>

          <wa-carousel style="--aspect-ratio: 16/4; " autoplay loop navigation pagination autoplay-interval="5000">
            <wa-carousel-item>
              <img id="carousel-item-0" src="{{ STATIC_BASE_URL }}{{ result.pageImageUri }}">
            </wa-carousel-item>
            <wa-carousel-item>
              <img id="carousel-item-1" src="{{ STATIC_BASE_URL }}/jpg/nedsi-conference-2025.jpg">
        
            </wa-carousel-item>
          </wa-carousel>

          <p>
            Rejoignez-nous à Philadelphie, PA, du jeudi 9 avril au samedi 11 avril 2026 à la conférence NEDSI 2026, 
            avec d'autres universitaires et praticiens intéressés par l'application de 
            méthodes quantitatives et comportementales aux problèmes de la société à travers les technologies émergentes. 
          </p>
          <p>
            Nous présenterons la théorie de la programmation SPINE, [cite: 6]
            une forme d'indexation de code IA souveraine, locale et sur l'appareil, ainsi que la génération de code open source de sites Web axés sur les données et de jumeaux numériques. [cite: 6]
          </p>
          <p>
            Vous pouvez lire le document de recherche <a href="https://docs.google.com/document/d/1whyZNMopmAQ14XZCxC_qfswcBgrmaKoRRcFUvy6GNLw/edit?usp=sharing">Génération de code API de sites Web « Zero Trust » axés sur les données et de jumeaux numériques avec la théorie de la programmation SPINE ici</a>. [cite: 7]
          </p>

          <wa-card with-header>
            <div slot="header">
              <div class="wa-flank ">
                <i class="fa-duotone fa-regular fa-conveyor-belt fa-8x "></i>
                <div>
                  <h2 class="brand-font anchor-heading">
   
                    À propos de la conférence [cite: 8]
                    L'IA générative pour améliorer la résilience de la chaîne d'approvisionnement [cite: 8]
                  </h2>
                </div>
              </div>
       
            </div>
            <div class="wa-stack ">
              <div>
                <p>
                  Le thème de la conférence 2026, L'avenir des sciences de la décision : Complexité, Innovation, Durabilité, nous invite à réfléchir de manière critique et constructive sur l'évolution de notre domaine et le rôle qu'il doit jouer pour relever les défis [cite: 10]
                  organisationnels et sociétaux modernes. [cite: 10]
                  Le programme comprendra un mélange dynamique de sessions de communication, de tables rondes, d'ateliers interactifs et d'affiches d'étudiants, l'accent étant mis sur la collaboration interdisciplinaire et l'application dans le monde réel. [cite: 11]
                  Une conférence NEDSI est un forum permettant aux universitaires et aux praticiens de présenter leurs recherches dans leurs domaines d'expertise et de s'entrelacer vers de nouveaux horizons ; 
                  c'est là que le réseautage saillant se produit et que des amitiés se nouent pour la vie. 
                </p>
              </div>
            </div>
          </wa-card>
        </div>
