---
components:
  schemas:
    Feed
      "$ref": "http://localhost:10230/static/fiware/Feed/model.yaml#/Feed
    Feeder
      "$ref": "http://localhost:10230/static/fiware/Feeder/model.yaml#/Feeder
    FeedingOperation
      "$ref": "http://localhost:10230/static/fiware/FeedingOperation/model.yaml#/FeedingOperation
    FishingDock
      "$ref": "http://localhost:10230/static/fiware/FishingDock/model.yaml#/FishingDock
    FishPopulation
      "$ref": "http://localhost:10230/static/fiware/FishPopulation/model.yaml#/FishPopulation
    FishProcessing
      "$ref": "http://localhost:10230/static/fiware/FishProcessing/model.yaml#/FishProcessing
info:
  description: >+
openapi: "3.0.0"
paths:
  /ngsi-ld/v1/entities:
    get:
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters:
        - in: query
          name: type
          required: true
          schema:
            enum:
              - TrafficFlowObserved
            type: string
      responses:
        "200":
          content:
            "application/ld+json":
              examples:
                keyvalues:
                  summary: "Key-Values Pairs"
                  value:
                    - "$ref": "http://localhost:10230/static/fiware/Feed/examples/example.json"
                    - "$ref": "http://localhost:10230/static/fiware/Feeder/examples/example.json"
                    - "$ref": "http://localhost:10230/static/fiware/FeedingOperation/examples/example.json"
                    - "$ref": "http://localhost:10230/static/fiware/FishingDock/examples/example.json"
                    - "$ref": "http://localhost:10230/static/fiware/FishPopulation/examples/example.json"
                    - "$ref": "http://localhost:10230/static/fiware/FishProcessing/examples/example.json"
                normalized:
                  summary: "Normalized NGSI-LD"
                  value:
                    - $ref: "http://localhost:10230/static/fiware/Feed/examples/example-normalized.json"
                    - $ref: "http://localhost:10230/static/fiware/Feeder/examples/example-normalized.json"
                    - $ref: "http://localhost:10230/static/fiware/FeedingOperation/examples/example-normalized.json"
                    - $ref: "http://localhost:10230/static/fiware/FishingDock/examples/example-normalized.json"
                    - $ref: "http://localhost:10230/static/fiware/FishPopulation/examples/example-normalized.json"
                    - $ref: "http://localhost:10230/static/fiware/FishProcessing/examples/example-normalized.json"
          description: OK
      tags:
        - ngsi-ld
tags:
  description: "NGSI-LD Linked-data Format"
  name: ngsi-ld
