        <div class="wa-stack purple-blue-background-headers ">

          <wa-tooltip for="carousel-item-0" placement="left" hoist>Presenting the Smart Aquaculture workshop at the the Generative AI to Enhance Supply Chain Resilience NEDSI 2025 research conference in Hershey, Pennsylvania. </wa-tooltip>

          <wa-carousel style="--aspect-ratio: 16/4; " autoplay loop navigation pagination autoplay-interval="5000">
            <wa-carousel-item>
              <a id="carousel-item-0" href="">
                <img src="{{ STATIC_BASE_URL }}/jpg/nedsi-conference-2025.jpg">
              </a>
            </wa-carousel-item>
          </wa-carousel>

          <wa-card class="purple-blue-background ">
            <div class="wa-stack ">
              <div class="wa-flank ">
                <i class="fa-duotone fa-regular fa-browser fa-8x "></i>
                <div>
                  <h1 class="brand-font">
                    Learn how to develop an open source data-driven website for Smart Aquaculture with generative AI in the cloud
                  </h1>
                  <h2 class="brand-font">
                    with the {{ result.name }}
                  </h2>
                </div>
              </div>
              <div>
                This course will become available for participants at the 
                <a href="https://nedsi.decisionsciences.org/registration/">2025 Northeast Decision Sciences Institute Annual Conference</a>
                in Hershey, Pennsylvania, USA Thursday March 27, 2025 — Saturday March 29, 2025 
              </div>
            </div>
          </wa-card>

          <wa-card with-header>
            <div slot="header">
              <h2 class="brand-font anchor-heading">
                What is the {{ result.name }}?
              </h2>
              <p>
                Learn how to develop custom Smart Aquaculture data-driven websites and open APIs in the cloud, 
                and build your own secure IoT smart platform with generative AI, zero-trust access control, and interactive dashboards. 
              </p>
            </div>

            <div class="wa-stack ">

              <div>
                <div class="wa-flank ">
                  <i class="fa-duotone fa-regular fa-code"></i>
                  <h3>
                    Modern development tools
                  </h3>
                </div>
                <div>
                  Access your VSCode developer workbench in the browser, it doesn't matter your laptop's operating system. 
                </div>
              </div>

              <div>
                <div class="wa-flank ">
                  <i class="fa-duotone fa-regular fa-cloud-arrow-up"></i>
                  <h3>
                    Automate tasks
                  </h3>
                </div>
                <div>
                  Use Ansible automation to generate all of the boilerplate code for your Smart Aquaculture site, and customize it along the way. 
                </div>
              </div>

              <div>
                <div class="wa-flank ">
                  <i class="fa-duotone fa-regular fa-cloud-arrow-up"></i>
                  <h3>
                    Learn reactive programming
                  </h3>
                </div>
                <div>
                  Learn how to build reactive asynchronous Java code, OpenAPIs, database scripts, and Smart Aquaculture data. 
                </div>
              </div>

              <div>
                <div class="wa-flank ">
                  <i class="fa-duotone fa-regular fa-cloud-arrow-up"></i>
                  <h3>
                    Build interactive dashboards
                  </h3>
                </div>
                <div>
                  Visualize your Smart Aquaculture data in event-driven, interactive dashboards and maps. 
                </div>
              </div>

              <div>
                <div class="wa-flank ">
                  <i class="fa-duotone fa-regular fa-cloud-arrow-up"></i>
                  <h3>
                    Cloud-native microservices
                  </h3>
                </div>
                <div>
                  Interact with modern microservices in the cloud like: 
                </div>
                <ul>
                  <li>
                    PostgreSQL Database for transactional data storage
                  </li>
                  <li>
                    Apache Zookeeper Cluster Manager for event bus messaging
                  </li>
                  <li>
                    Apache Solr Search Engine for autosuggest and searchable APIs
                  </li>
                  <li>
                    Keycloak Single Sign-On for fine-grain access control to Smart Aquaculture data
                  </li>
                  <li>
                    FIWARE Context Broker for open source IoT edge device standards
                  </li>
                </ul>
              </div>

            </div>
          </wa-card>

          <wa-card with-header>
            <div slot="header">
              <div class="wa-flank ">
                <i class="fa-duotone fa-regular fa-conveyor-belt fa-8x "></i>
                <div>
                  <h2 class="brand-font anchor-heading">
                    About the conference
                    Generative AI to Enhance Supply Chain Resilience
                  </h2>
                </div>
              </div>
            </div>
            <div class="wa-stack ">
              <div>
                <p>
                  A NEDSI conference is a forum for scholars and practitioners to present their research and keep abreast of their areas of expertise and interlace into new horizons, 
                  it is where salient networking occurs, and friendships are made for a lifetime. 
                  Conference participants have stated that they enjoy the amicable nature at NEDSI conferences; over 200 participants are expected at this year’s event. 
                </p>
              </div>
            </div>
          </wa-card>
        </div>
